CREATE TABLE labs(
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	code VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(255),

	editorId BIGINT,
	CONSTRAINT fk_editor FOREIGN KEY (editorId)
											REFERENCES editors(id),

	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
