CREATE TABLE labs(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	code VARCHAR(255) NOT NULL UNIQUE,
	description VARCHAR(255),
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
