CREATE TABLE lecturers (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	gender ENUM('male', 'female') NOT NULL,
	labId INT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT fk_lab FOREIGN KEY (labId) REFERENCES labs(id)
);