CREATE TABLE lecturers (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	description VARCHAR(255), 
	gender VARCHAR(255), 
	labId BIGINT,

	editorId BIGINT,
	CONSTRAINT fk_editor FOREIGN KEY (editorId)
											REFERENCES editors(id),

	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT fk_lab FOREIGN KEY (labId) REFERENCES labs(id) 
		ON UPDATE CASCADE
		ON DELETE SET NULL
);