CREATE TABLE traits (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
						 ON UPDATE CURRENT_TIMESTAMP NOT NULL
);